name: Docker Image CI

on:
  push:
    branches: [ test ]
  pull_request:
    types: [ labeled ]

jobs:
  build-docker:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        id: setvars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Executor
        id: docker_build_executor
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: executor
          tags: latest
