name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: prover
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.ACCESS_TOKEN }}
        
