name: Build docker image and run node tests

on:
  push:
    branches: [ test ]

jobs:
  build-docker:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Executor
        id: docker_build_executor
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: test
          tags: latest
